name: Analyze Logs and Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  analyze-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install json

      - name: Run finding_IP script
        env:
          JSON_FILE: ./path/to/ip_logs.json  # Make sure the file is included in your repo or accessible
        run: python finding_IP.py

      - name: Notify via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Log Analysis Results"
          body: "The log analysis has been completed. Check the results in the Actions logs."
          to: recipient@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
