name: Run Chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  run-chatbot:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Inject secrets into the .env file
    - name: Create .env file
      run: |
        echo "PORT=${{ secrets.PORT }}" > .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "OTHER_ENV_VARIABLE=${{ secrets.OTHER_ENV_VARIABLE }}" >> .env

    # Step 5: Start the chatbot server
    - name: Run Vicky Server
      run: |
        nohup python vicky_server.py > server_log.txt 2>&1 &
        sleep 5
        curl -f http://localhost:${{ secrets.PORT }} || exit 1 # Check if server is up
